url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Freelance Web Developer Reddit" # the name of your site, e.g. ACME Corp.
description: 

sidebar_text_1: 
